### PR TITLE
Upgrade to hybrid element

### PR DESCRIPTION
**Pull request by Mihaiii**
NOT FOR MERGE

There is a problem with it when `mode` is `code`. 
 
Related to https://github.com/Starcounter/RebelsLounge/issues/140 .

### CODE REVIEW

**Comment by Mihaiii** [comment]
I spent to much time on this already and have to move on to other things.
@tomalec I need help with this one, sorry.

**Comment by tomalec** [comment]
@Mihaiii  please review my changes

**Comment by Mihaiii** [comment]
@tomalec Yes, the layout is ok now. Thank you for the update!
It is still not for merge since the user can't change the mode when another selected from the drop-down list.
I'll look into it.

**Comment by tomalec** [comment]
It seems to be a bug/misbehavior of JSONEditor itself. Shadow DOM v1 scopes the events and current JSONEditor implementation `addEventListener` to the `window` from which perspective `event.target` is no longer clicked menu item, but shadow host.
see https://github.com/josdejong/jsoneditor/issues/447

**Comment by tomalec** [comment]
@Mihaiii do we use modes extensively in our apps or `starcounter-debug-aid`? if not we could merge this PR, then wait for https://github.com/josdejong/jsoneditor/pull/448 to be merged or fixed in `JSONEditor` otherwise.

**Comment by Mihaiii** [comment]
Yup, you're right.
Merging. :)

**Pull request merged**
